application: sneaky-main
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: markupsafe
  version: "0.15"
- name: jinja2
  version: latest

